version: '3.8'

services:

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drs_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - ./backend:/app

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: drs_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      # Point to the local backend service
      - API_URL=http://backend:8000/api

# Volumes
volumes:
  postgres_data:
  pgadmin_data:
